#! /bin/bash

# Copyright (C) 2011 Ian Zimmerman <itz@buug.org>

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the conditions spelled out in
# the file LICENSE are met.

set -e

ce=ctl.equal
eqd=~/.aectl
pidfile=$eqd/.eq.pid

intersect()
{
    for p in $* ; do echo $p ; done | sort | uniq -d
}

signal_mixer()
{
    local eq_pid
    local eq_kids
    local mixers
    local m
    eq_pid=$1
    eq_kids=$( ps --no-header --ppid $eq_pid -o pid )
    mixers=$( ps --no-header -C alsamixer -o pid )
    m=$( intersect $eq_kids $mixers )
    if [ -n $m ] ; then kill -USR1 $m ; fi
}

case "$1" in
    save)
        if [ $# -ge 2 ] ; then exec >$2 ; fi
        ctlnames=$( amixer -D $ce scontrols | sed -e "s:.*'\(.*\)'.*:\1:" -e "s: :_:g" )
        for c in $ctlnames ; do
            rc=$( echo "$c" | sed -e "s:_: :g" )
            val=$( amixer -D $ce get "$rc" | grep -m1 '%' | sed -e "s:.*[^0-9]\([0-9][0-9]*\)%.*:\1:" )
            echo "$c:$val"
        done
        ;;
    load)
        if [ $# -ge 2 ] ; then exec <$2 ; fi
        while read line ; do
            c=$( echo $line | cut -d: -f1 )
            rc=$( echo "$c" | sed -e "s:_: :g" )
            val=$( echo $line | cut -d: -f2 )
            amixer -D $ce set "$rc" "${val}%" > /dev/null
        done
        if [ -f $pidfile ] ; then
            eq_pid=$( cat $pidfile )
            signal_mixer $eq_pid
        fi
        ;;
    *)
        echo "usage: $0 (save|load)" >&2
        exit 2
        ;;
esac

