#! /bin/sh

# Copyright (C) 2011 Ian Zimmerman <itz@buug.org>

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the conditions spelled out in
# the file LICENSE are met.

# a stupid wrapper needed on my system to authorize mpd user to use $DISPLAY

set -e
xauth nlist | su -s /bin/sh -c 'xauth nmerge -' mpd
exec pyael
